async (page) => {
    const checks = [];
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if(message.type()==='error')errors.push(message.text().slice(0,250)); });
    const check = (name,condition) => { if(!condition)throw new Error(name);checks.push(name); };
    await page.setViewportSize({width:1440,height:1050});
    await page.goto('http://localhost:5173/');
    await page.locator('.post-row').first().waitFor();
    await page.waitForFunction(() => [...document.querySelectorAll('.rare-cell:not(.unavailable)')].every(el=>getComputedStyle(el).opacity==='1'));
    await page.waitForFunction(() => document.documentElement.dataset.theme && document.querySelector('.icon-button')?.getAttribute('aria-label') === (document.documentElement.dataset.theme==='dark'?'Switch to light theme':'Switch to dark theme'));
    await page.evaluate(()=>document.fonts.ready);
    await page.locator('.activity-section').evaluate(el=>Promise.all(el.getAnimations().map(a=>a.finished)));
    const light = page.getByRole('button',{name:'Switch to dark theme'});
    if(await light.count())await light.click();
    await page.screenshot({path:'output/playwright/desktop-verified.png',fullPage:true});
    check('No desktop overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    check('Rare UI fork is rendered',await page.locator('[data-slot="github-activity"]').count()===1);
    check('Calendar has daily cells',await page.locator('.rare-cell').count()>=365);
    await page.getByRole('tab',{name:'Trickles',exact:true}).click();
    check('Trickles exclude confirmations',await page.locator('.post-row .badge.confirmed').count()===0);
    await page.getByRole('button',{name:'View context',exact:true}).first().click();
    check('Reply context expands',await page.locator('.post-detail blockquote').count()>0);
    check('Parent source is linked',await page.locator('.post-detail blockquote a').first().getAttribute('href').then(x=>x.startsWith('https://x.com/')));
    await page.getByRole('tab',{name:'Resets',exact:true}).click();
    check('Resets exclude hints',await page.locator('.post-row .badge.hint').count()===0);
    await page.getByRole('tab',{name:'All',exact:true}).click();
    const before=await page.locator('.post-row').count();
    await page.getByRole('button',{name:'Load older updates'}).click();
    check('Older updates load',await page.locator('.post-row').count()>before);
    await page.getByRole('button',{name:'12 Sept 2026: Full reset',exact:true}).click();
    check('Calendar filters feed',await page.getByRole('button',{name:'Clear date filter',exact:true}).count()===1);
    check('Selected day contains its confirmation',await page.locator('.post-row').filter({hasText:'Reset all propagated'}).count()===1);
    await page.getByRole('button',{name:'Clear date filter',exact:true}).click();
    await page.getByRole('combobox',{name:'Activity period'}).click();
    await page.getByRole('option',{name:'2025',exact:true}).click();
    await page.getByRole('button',{name:'17 Sept 2025: Full reset',exact:true}).waitFor();
    check('Year selection works',await page.getByRole('button',{name:'17 Sept 2025: Full reset',exact:true}).count()===1);
    await page.getByRole('combobox',{name:'Activity period'}).click();
    await page.getByRole('option',{name:'Past year',exact:true}).click();
    await page.getByRole('button',{name:'12 Sept 2026: Full reset',exact:true}).waitFor();
    await page.getByRole('button',{name:'12 Sept 2026: Full reset',exact:true}).focus();
    await page.keyboard.press('ArrowLeft');
    check('Calendar supports arrow keys',await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')?.startsWith('5 Sept 2026')));
    await page.getByRole('button',{name:'Switch to light theme'}).click();
    await page.screenshot({path:'output/playwright/light-verified.png',fullPage:true});
    await page.reload();
    await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');
    check('Theme preference survives reload',true);
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:'output/playwright/mobile-light.png',fullPage:true});
    check('No mobile overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    check('Mobile calendar scrolls independently',await page.locator('.calendar-scroll').evaluate(el=>el.scrollWidth>el.clientWidth));
    await page.getByRole('button',{name:'Switch to dark theme'}).click();
    await page.screenshot({path:'output/playwright/mobile-dark.png',fullPage:true});
    await page.getByRole('tab',{name:'Trickles',exact:true}).click();
    await page.getByRole('button',{name:'View context',exact:true}).first().click();
    check('Mobile reply context works',await page.locator('.post-detail blockquote').count()>0);
    await page.screenshot({path:'output/playwright/mobile-context.png',fullPage:true});
    await page.emulateMedia({reducedMotion:'reduce'});
    await page.reload();
    await page.waitForFunction(()=>[...document.querySelectorAll('.rare-cell:not(.unavailable)')].every(el=>getComputedStyle(el).opacity==='1'));
    check('Reduced-motion calendar remains visible',true);
    await page.setViewportSize({width:1440,height:1050});
    await page.getByRole('tab',{name:'All',exact:true}).click();
    check('No browser runtime errors',errors.length===0);
    return {checks,errors};
}
